package com.example.model

data class VideoStream(
    val url: String,
    val quality: String, // e.g. "2160p (4K)", "1440p (2K)", "1080p60", "720p", "480p", "360p"
    val format: String = "MP4", // MP4, WEBM
    val codec: String = "avc1 / vp9 / av01",
    val bitrate: Long = 0,
    val fps: Int = 30,
    val width: Int = 1920,
    val height: Int = 1080,
    val sizeMb: Double = 0.0,
    val isVideoOnly: Boolean = false
)

data class AudioStream(
    val url: String,
    val quality: String, // e.g. "320 kbps (HQ)", "160 kbps", "128 kbps", "64 kbps"
    val format: String = "M4A", // M4A, OPUS, MP3
    val codec: String = "mp4a / opus",
    val bitrate: Long = 0,
    val sizeMb: Double = 0.0,
    val sampleRate: Int = 44100
)

data class SubtitleItem(
    val language: String,
    val url: String,
    val format: String = "vtt",
    val isAutoGenerated: Boolean = false
)

data class SponsorSegment(
    val category: String,
    val startSeconds: Double,
    val endSeconds: Double
)

data class NewPipeStreamInfo(
    val videoId: String,
    val title: String,
    val uploaderName: String,
    val uploaderUrl: String = "",
    val uploaderAvatar: String = "",
    val uploaderSubscriberCount: String = "",
    val uploaderVerified: Boolean = false,
    val description: String = "",
    val uploadDate: String = "",
    val durationSeconds: Long = 0,
    val viewCount: Long = 0,
    val likeCount: Long = 0,
    val dislikeCount: Long = 0,
    val videoStreams: List<VideoStream> = emptyList(),
    val audioStreams: List<AudioStream> = emptyList(),
    val hlsUrl: String? = null,
    val dashUrl: String? = null,
    val subtitles: List<SubtitleItem> = emptyList(),
    val chapters: List<KeyMoment> = emptyList(),
    val relatedStreams: List<VideoItem> = emptyList(),
    val sponsorSegments: List<SponsorSegment> = emptyList(),
    val extractorSource: String = "NewPipe Extractor • Direct YouTube",
    val extractedAt: Long = System.currentTimeMillis()
)
